DOMAIN = "chastify"
CONF_TOKEN = "token"
BASE_URL = "https://chastify.net/api/apps/v1"
DEFAULT_SCAN_INTERVAL = 30

SERVICE_ACTION = "action"
SERVICE_ADD_TIME = "add_time"
SERVICE_REMOVE_TIME = "remove_time"
SERVICE_APPLY_TIME = "apply_time"
SERVICE_FREEZE = "freeze"
SERVICE_UNFREEZE = "unfreeze"
SERVICE_HYGIENIC_UNLOCK = "hygienic_unlock"
SERVICE_LOG = "log_custom"
SERVICE_DEVICE_COMMAND = "device_command"

ATTR_NAME = "name"
ATTR_PARAMS = "params"
ATTR_SECONDS = "seconds"
ATTR_DURATION_SECONDS = "duration_seconds"
ATTR_TITLE = "title"
ATTR_DESCRIPTION = "description"
ATTR_ROLE = "role"
ATTR_ICON = "icon"
ATTR_COLOR = "color"
ATTR_COMMAND = "command"
